---
##################################################
# 実行するタスクを定義する
##################################################

- name: EPELリポジトリをインストール
  yum:
    name: epel-release
    state: present
  become: yes # use sudo
  tags:
    - redis

- name: Remiリポジトリをインストール
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
  become: yes # use sudo
  tags:
    - redis

- name: Redisをインストール
  yum:
    name:
      - redis
    state: present
    enablerepo: epel,remi
  become: yes # use sudo
  tags:
    - redis
