---
##################################################
# Define tasks
##################################################

- name: Install Redis
  package:
    name: redis
    state: present

- name: Start redis and Enable autostart
  systemd:
    name: redis
    state: started
    enabled: yes
