---
##################################################
# 実行するタスクを定義する
##################################################

- name: Redisをインストール
  apt:
    name:
      - redis
    state: latest
  become: yes # use sudo
  tags:
    - redis
