---
##################################################
# Define tasks
##################################################

- name: Install Redis
  apt:
    name: redis
    state: present
    update_cache: yes
  become: yes # use sudo
