---
##################################################
# ハンドラを定義する
##################################################

- name: restart_apache_redhat
  systemd:
    name: httpd
    state: restarted
  become: yes # use sudo

- name: restart_apache_debian
  systemd:
    name: apache2
    state: restarted
  become: yes # use sudo
