---
##################################################
# ハンドラを定義する
##################################################

- name: restart_apache
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: restart_apache
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"
