---
##################################################
# ハンドラを定義する
##################################################

- name: restart_apache_redhat
  systemd:
    name: httpd
    state: restarted

- name: restart_apache_debian
  systemd:
    name: apache2
    state: restarted
