---
##################################################
# Define tasks
##################################################

- name: Install repository of nginx
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
  tags:
    - nginx

- name: Install Nginx
  yum:
    name: nginx
    state: present
  tags:
    - nginx

- name: Start Nginx and enable autostart
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx
