---
##################################################
# Define tasks
##################################################

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes # use sudo
