---
##################################################
# Define tasks
##################################################

- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  become: yes # use sudo
