---
##################################################
# Define tasks
##################################################

- name: Deploy Application code.
  git:
    repo: "https://github.com/nagatax/laravel-app-for-deploy.git"
    dest: "{{ deploy_laravel_root }}"
    version: master
    accept_hostkey: True

# - name: Composerで依存解決
#   composer:
#     command: install
#     working_dir: "{{ deploy_laravel_root }}"
#     no_dev: {{ not deploy_laravel_debug }}
#   tags:
#     - deploy

# - name: .envテンプレートを転送
#   template:
#     src: files/deploy/.env.j2
#     dest: "{{ deploy_laravel_root }}/.env"
#   tags:
#     - deploy

# - name: データベースのマイグレーション
#   shell: php artisan migrate --env {{ deploy_laravel_env }} --force
#   args:
#     chdir: "{{ deploy_laravel_root }}"
#   when: deploy_laravel_debug
#   tags:
#     - deploy

# - name: サンプルデータを登録
#   shell: php artisan db:seed --env {{ deploy_laravel_env }} --force
#   args:
#     chdir: "{{ deploy_laravel_root }}"
#   when: deploy_laravel_debug
#   tags:
#     - deploy

# - name: Laravelを最適化
#   shell: php artisan optimize chdir={{ deploy_laravel_root }}
#   when: not deploy_laravel_debug
#   tags:
#     - deploy
