---
##################################################
# 変数のデフォルト値を定義する
##################################################

mysql_port: "3306"
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: "Homestead0$"
mysql_repository: "https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm"
mysql_service: "mysqld"
