---
##################################################
# Define tasks
##################################################

- name: laravelがセットアップ済みか確認
  stat:
    path: "{{ document_root }}/artisan"
    get_checksum: false
    get_md5: false
  register: is_laravel_folder
  become: yes
  become_user: "{{ app_own_user }}"

- name: Laravel Installerのインストール
  composer:
    command: require
    global_command: yes
    arguments: laravel/installer
  become: yes
  become_user: "{{ app_own_user }}"
  when: not is_laravel_folder.stat.exists

- name: laravelのセットアップ
  shell: |
    ~/.config/composer/vendor/bin/laravel new
    chmod +w storage bootstrap/cache
  args:
    chdir: "{{ document_root }}" 
  become: yes
  become_user: "{{ app_own_user }}"
  when: not is_laravel_folder.stat.exists

- name: PHP Coding Standards Fixer
  composer:
    command: require
    no-dev: yes
    arguments: friendsofphp/php-cs-fixer
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: PHP_CodeSniffer
  composer:
    command: require
    no-dev: yes
    arguments: squizlabs/php_codesniffer
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: PHP Mess Detector
  composer:
    command: require
    no-dev: yes
    arguments: phpmd/phpmd=@stable
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install Horizon
  composer:
    command: require
    arguments: laravel/horizon
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install laravel-mix
  yarn:
    path: "{{ document_root }}"
  become: yes

- name: Install laravel-debugbar
  composer:
    command: require
    no-dev: yes
    arguments: barryvdh/laravel-debugbar
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install laravel helper
  composer:
    command: require
    no-dev: yes
    arguments: barryvdh/laravel-ide-helper
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: create helper file
  command: php artisan ide-helper:generate
  args:
    chdir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install Laravel Telescope
  composer:
    command: require
    no-dev: yes
    arguments: laravel/telescope
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: アセットの公開
  shell: |
    php artisan telescope:install
    php artisan migrate
  args:
    chdir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install predis
  composer:
    command: require
    no-dev: yes
    arguments: predis/predis
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"

- name: フォルダ権限の変更
  file:
    path: "{{ document_root }}"
    owner: apache
    group: apache
  become: yes
