---
##################################################
# Define tasks
##################################################

- name: Setup DB
  include_tasks: setupDb.yml
  tags:
    - laravel

- name: Setting of CentOS
  include_tasks: centos.yml
  when: ansible_os_family == "RedHat"
  tags:
    - laravel

- name: Setting of Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"
  tags:
    - laravel
