---
##################################################
# Define tasks
##################################################

- name: Setup DB
  include: setupDb.yml
  tags:
    - laravel

- name: Setting of CentOS
  include: centos.yml
  when: ansible_os_family == "RedHat"
  tags:
    - laravel

- name: Setting of Ubuntu
  include: ubuntu.yml
  when: ansible_os_family == "Debian"
  tags:
    - laravel
