---
##################################################
# Define tasks
##################################################

- name: Create Database
  mysql_db:
    name: "{{ app_db }}"
    state: present
  become: yes # use sudo

- name: MySQLユーザーを作成し，アプリケーションで使用するDBのすべての権限を与える
  mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_password }}"
    priv: "{{ app_db_user }}.*:ALL,GRANT"
    host: localhost
    state: present
  become: yes # use sudo
