---
##################################################
# Define tasks
##################################################

- name: Create homestead Database
  mysql_db:
    name: homestead
    state: present
  become: yes # use sudo

- name: MySQLユーザー homestead を作成し，homestead.* にすべての権限を与える
  mysql_user:
    name: homestead
    password: "{{ mysql_db_password }}"
    priv: "homestead.*:ALL,GRANT"
    host: localhost
    state: present
  become: yes # use sudo
