---
##################################################
# Define tasks
##################################################

- name: Install apache
  yum:
    name: httpd
    state: present

- name: Copy httpd.conf to server's directory
  template:
    src: centos/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_apache_redhat

- name: Copy vhosts.conf to server's directory
  template:
    src: centos/vhosts.conf.j2
    dest: /etc/httpd/conf.d/vhosts.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_apache_redhat

- name: Start apache and Enable autostart
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Allow ports for firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 80
    - 443
