---
##################################################
# 実行するタスクを定義する
##################################################

- name: Install apache
  yum:
    name: httpd
    state: present
  become: yes # use sudo
  tags:
    - apache

- name: Copy httpd.conf to server's directory
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
  become: yes # use sudo
  tags:
    - apache
  notify:
    - restart_apache

- name: Copy vhosts.conf to server's directory
  template:
    src: vhosts.conf.j2
    dest: /etc/httpd/conf.d/vhosts.conf
    owner: root
    group: root
    mode: 0644
  become: yes # use sudo
  tags:
    - apache
  notify:
    - restart_apache

- name: Start apache and Enable autostart
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes # use sudo
  tags:
    - apache
