---
##################################################
# Define executable roles
##################################################

- name:   Install packages
  hosts:  all
  connection: local
  roles:
    - apache
    - docker
    - go
    - jenkins
    - laravel
    - mailhog
    - mariadb
    - memcached
    - minio
    - mongodb
    - nginx
    - php
    - redis
    - ruby
    - yarn
#    - deploy
