---
##################################################
# Define executable roles
##################################################

- name:   Install packages
  hosts:  all
  connection: local
  become: yes
  roles:
    - apache
    - docker
    - name: go
      tags: go
    - jenkins
    - laravel
    - name: mailhog
      tags: mailhog
    - mariadb
    - memcached
    - minio
    - mongodb
    - nginx
    - php
    - redis
    - ruby
    - yarn
#    - deploy
