---
##################################################
# Define executable roles
##################################################

- name:   Install common packages
  hosts:  all
  connection: local
  become: yes
  roles:
    - name: common/locale
      tags: locale
    - name: common/packages
      tags: packages
    - name: common/users
      tags: users
    - name: common/times
      tags: times
