---
##################################################
# ハンドラを定義する
##################################################

- name: restart_mariadb
  systemd:
    name: mariadb
    state: restarted
  become: yes # use sudo
