---
##################################################
# Define tasks
##################################################

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Start ntpd service and enable autostart
  systemd:
    name: "{{ ntp_service }}"
    state: started
    enabled: yes
