---
##################################################
# Define default values
##################################################

required_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

docker_package: docker-ce
