---
##################################################
# Define tasks
##################################################

- name: Import repository key
  yum_repository:
    name: mariadb
    description: MariaDB Repo
    baseurl: http://yum.mariadb.org/10.3/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    file: MariaDB
  become: yes # use sudo

- name: Install MariaDB
  yum:
    name:
      - galera
      - rsync
      - MariaDB-client
      - MariaDB-server
      - MySQL-python
    state: present
    enablerepo: mariadb
  become: yes # use sudo

- name: Copy my.cnf template
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  become: yes # use sudo
  notify:
    - restart_mariadb

- name: Enable MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes
  become: yes # use sudo

- name: Set root's password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
  become: yes # use sudo

- name: Copy .my.cnf template
  template:
    src: my.client.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644
  become: yes # use sudo
