---
##################################################
# Define tasks
##################################################

- name: Add Jenkins Repository.
  shell: |
    wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
  become: yes # use sudo

- name: Import key.
  shell: |
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  become: yes # use sudo

- name: Install OpenJDK
  yum:
    name:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
    state: latest
  become: yes # use sudo

- name: Install jenkins packages
  yum:
    name:
      - jenkins
    state: latest
  become: yes # use sudo
