---
##################################################
# Define tasks
##################################################

- name: Import epel repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Import remi repository
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- block:
  - name: Update package's information
    apt:
      update_cache: yes
  - name: Update packages
    apt:
      name: "*"
      state: latest
  when: ansible_os_family == "Debian"

- name: Install base packages
  package:
    name:
      - curl
      - git
      - ntp
      - unzip
      - vim
      - wget
    state: latest

- name: SELinux permissived
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat" and ansible_selinux.config_mode == 'enforcing'
