---
##################################################
# Define tasks
##################################################

- name: Import epel repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Import remi repository
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- block:
  - name: Update pakages
    yum:
      name: '*'
      state: latest
      update_cache: yes
  - name: Install base packages and update pakages
    yum:
      name: '{{ common_pkgs }}'
      state: latest
      update_cache: yes
  when: ansible_os_family == "RedHat"

- block:
  - name: Update packages
    apt:
      update_cache: yes
  - name: Install base packages and update pakages
    apt:
      name: '{{ common_pkgs }}'
      state: latest
      update_cache: yes
  when: ansible_os_family == "Debian"

- name: SELinux permissived
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat" and ansible_selinux.config_mode == 'enforcing'

- block:
  - name: firewalld のインストール 
    yum:
      name: firewalld
      state: latest

  - name: Open http port
    firewalld:
      zone: public
      service: http
      permanent: yes
      state: enabled

  - name: Open http port
    firewalld:
      zone: public
      service: https
      permanent: yes
      state: enabled

  - name: Open mysql port
    firewalld:
      zone: public
      service: mysql
      permanent: yes
      state: enabled

  - name: Restart a firewalled
    become: yes
    systemd:
      name: firewalld
      state: restarted
