---
##################################################
# Define tasks
##################################################

- name: Install Golang
  yum:
    name: golang
    state: present
  become: yes # use sudo
