---
##################################################
# 実行するタスクを定義する
##################################################

- name: Install EPEL repogitry
  yum:
    name: epel-release
    state: present
  tags:
    - go

- name: Install Golang
  yum:
    name: golang
    state: present
  tags:
    - go
