---
##################################################
# 実行するタスクを定義する
##################################################

- name: EPELリポジトリをインストール
  yum:
    name: epel-release
    state: present
  tags:
    - go

- name: Goをインストール
  yum:
    name: golang
    state: present
  tags:
    - go
