---
##################################################
# 実行するタスクを定義する
##################################################

- name: Install Golang
  apt:
    name: golang
    state: latest
  tags:
    - go
