---
##################################################
# 実行するタスクを定義する
##################################################

- name: NodeJSのリポジトリを登録
  shell: |
    curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
  become: yes # use sudo
  tags:
    - yarn

- name: NodeJSのインストール
  yum:
    name: nodejs
    state: latest
  become: yes # use sudo
  tags:
    - yarn

- name: Yarnのリポジトリを登録
  shell: |
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
  become: yes # use sudo
  tags:
    - yarn

- name: Yarnをインストール
  shell: curl -sL https://rpm.nodesource.com/setup_11.x | bash - && yum install nodejs
  become: yes # use sudo
  tags:
    - yarn
