---
##################################################
# 実行するタスクを定義する
##################################################

- name: NodeJSのリポジトリを登録
  shell: |
    curl --silent --location https://deb.nodesource.com/setup_8.x | bash -
  become: yes # use sudo
  tags:
    - yarn

- name: NodeJSのインストール
  apt:
    name: nodejs
    state: latest
  become: yes # use sudo
  tags:
    - yarn

- name: Yarnのリポジトリを登録
  shell: |
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  become: yes # use sudo
  tags:
    - yarn

- name: Yarnをインストール
  shell: |
    apt update && apt install yarn
  become: yes # use sudo
  tags:
    - yarn
