---
##################################################
# Define tasks
##################################################

- name: Dockerをインストール
  yum:
    name:
      - docker
      - net-tools
    state: present
  become: yes # use sudo

- name: Dockerを起動、自動起動を有効化
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes # use sudo

- name: Docker Composeのインストール
  shell: |
    wget -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -O /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  become: yes # use sudo
