---
##################################################
# Define tasks
##################################################

- name: Set locale
  command: localectl set-locale {{ base_locale }}
  become: yes # use sudo

- name: Set timezone
  command: timedatectl set-timezone {{ base_timezone }}
  become: yes # use sudo

- name: Update all packages to the latest version
  yum:
    name: '*'
    state: present
  become: yes # use sudo

- name: Install base packages
  yum:
    name:
      - curl
      - git
      - ntp
      - unzip
      - vim
      - wget
    state: present
  become: yes # use sudo

- name: Start ntpd service and enable autostart
  systemd:
    name: ntpd
    state: started
    enabled: yes
  become: yes # use sudo
