---
##################################################
# Define tasks
##################################################

- name: Set locale
  command: localectl set-locale {{ base_locale }}
  become: yes # use sudo

- name: Set timezone
  command: timedatectl set-timezone {{ base_timezone }}
  become: yes # use sudo

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: yes # use sudo

- name: Install base packages
  apt:
    name:
      - curl
      - git
      - ntp
      - unzip
      - vim
    state: latest
  become: yes # use sudo

- name: Start ntpd service and enable autostart
  systemd:
    name: ntp
    state: started
    enabled: yes
  become: yes # use sudo
