---
##################################################
# Define tasks
##################################################

- name: ロケール設定
  command: localectl set-locale {{ base_locale }}
  become: yes # use sudo

- name: タイムゾーン設定
  command: timedatectl set-timezone {{ base_timezone }}
  become: yes # use sudo

- name: 基本パッケージをインストール
  apt:
    name:
      - curl
      - git
      - ntp
      - unzip
      - vim
    state: latest
  become: yes # use sudo

- name: ntpdを起動、自動起動の有効化
  systemd:
    name: ntp
    state: started
    enabled: yes
  become: yes # use sudo
