---
##################################################
# Define tasks
##################################################

- name: Install PHP
  yum:
    name:
      - php
      - php-bcmath
      - php-cli
      - php-common
      - php-devel
      - php-json
      - php-mcrypt
      - php-mbstring
      - php-mysqlnd
      - php-opcache
      - php-openssl
      - php-pdo
      - php-pear
      - php-pecl-memcache
      - php-pecl-memcached
      - php-pecl-zip
      - php-pgsql
      - php-process
      - php-tokenizer
      - php-xml
    state: present
    enablerepo: remi-php74
  when: ansible_os_family == "RedHat"

- name: Install PHP
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-bcmath
      - php-cli
      - php-common
      - php-curl
      - php-dev
      - php-fpm
      - php-json
      - php-mbstring
      - php-mysql
      - php-opcache
      - php-pear
      - php-pgsql
      - php-xdebug
      - php-xml
      - php-zip
    state: present
  when: ansible_os_family == "Debian"

- name: Copy custom php.ini
  copy:
    src: zzmyphp.ini
    dest: /etc/php.d/zzmyphp.ini
  when: ansible_os_family == "RedHat"

- name: Download a installer
  get_url:
    url: https://getcomposer.org/installer
    dest: ~/installer
    mode: 0755

- name: Install a Composer
  command: php ~/installer --install-dir=/usr/bin --filename=composer creates=/usr/bin/composer
