---
##################################################
# Define tasks
##################################################

- name: Install PHP
  apt:
    name:
      - php7.2
      - libapache2-mod-php7.2
      - php7.2-bcmath
      - php7.2-cli
      - php7.2-common
      - php7.2-curl
      - php7.2-dev
      - php7.2-fpm
      - php7.2-json
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-opcache
      - php-pear
      - php7.2-pgsql
      - php7.2-xml
      - php7.2-zip
    state: present

- name: Download a installer
  get_url:
    url: https://getcomposer.org/installer
    dest: ~/installer
    mode: 0755

- name: Install a Composer
  command: php ~/installer --install-dir=/usr/bin --filename=composer creates=/usr/bin/composer