---
##################################################
# Define tasks
##################################################

- name: Install memcached
  yum:
    name:
      - memcached
    state: present
  become: yes # use sudo
