---
##################################################
# 実行するタスクを定義する
##################################################

- name: memcachedをインストール
  yum:
    name:
      - memcached
    state: present
  tags:
    - memcached
