---
##################################################
# Define tasks
##################################################

- name: Install memcached
  apt:
    name: memcached
    state: latest
    update_cache: yes
  become: yes # use sudo
