---
##################################################
# Define tasks
##################################################

- name: Install memcached
  apt:
    name: memcached
    state: present
    update_cache: yes
