---
##################################################
# 実行するタスクを定義する
##################################################

- name: Download rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
  tags:
    - ruby

- name: Install rbenv
  shell: |
    echo 'export PATH=~/.rbenv/bin:$PATH' >> ~/.bash_profile
    ~/.rbenv/bin/rbenv init
    source ~/.bash_profile
  tags:
    - ruby

- name: Download ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
  tags:
    - ruby

- name: Install ruby-build
  shell: |
    ~/.rbenv/plugins/ruby-build/install.sh
  tags:
    - ruby

- name: Install Related Pakages
  yum:
    name: 
      - openssl-devel
      - readline-devel
      - zlib-devel
  tags:
    - ruby

- name: Install ruby
  shell: |
    ~/.rbenv/bin/rbenv install 2.6.0
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    ~/.rbenv/bin/rbenv global 2.6.0
  tags:
    - ruby
