---
##################################################
# Define tasks
##################################################

- name: Setting of CentOS
  include_tasks: centos.yml
  when: ansible_os_family == "RedHat"
  tags:
    - ruby

- name: Setting of Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"
  tags:
    - ruby
