---
##################################################
# Define tasks
##################################################

- name: Install MailHog
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64
    dest: /usr/local/bin/mailhog
    checksum: sha256:ba921e04438e176c474d533447ae64707ffcdd1230f0153f86cb188d348f25c0
    mode: 0755
  become: yes # use sudo
  tags:
    - mailhog
