---
##################################################
# Define tasks
##################################################

- name: Install MailHog
  shell: |
    wget https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64 -O /usr/local/bin/mailhog
    chmod +x /usr/local/bin/mailhog
  become: yes # use sudo
  tags:
    - mailhog
